// Generated by gencpp from file select_pcd/updated_coord.msg
// DO NOT EDIT!


#ifndef SELECT_PCD_MESSAGE_UPDATED_COORD_H
#define SELECT_PCD_MESSAGE_UPDATED_COORD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace select_pcd
{
template <class ContainerAllocator>
struct updated_coord_
{
  typedef updated_coord_<ContainerAllocator> Type;

  updated_coord_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  updated_coord_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::select_pcd::updated_coord_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::select_pcd::updated_coord_<ContainerAllocator> const> ConstPtr;

}; // struct updated_coord_

typedef ::select_pcd::updated_coord_<std::allocator<void> > updated_coord;

typedef boost::shared_ptr< ::select_pcd::updated_coord > updated_coordPtr;
typedef boost::shared_ptr< ::select_pcd::updated_coord const> updated_coordConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::select_pcd::updated_coord_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::select_pcd::updated_coord_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::select_pcd::updated_coord_<ContainerAllocator1> & lhs, const ::select_pcd::updated_coord_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::select_pcd::updated_coord_<ContainerAllocator1> & lhs, const ::select_pcd::updated_coord_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace select_pcd

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::select_pcd::updated_coord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::select_pcd::updated_coord_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::select_pcd::updated_coord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::select_pcd::updated_coord_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::select_pcd::updated_coord_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::select_pcd::updated_coord_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::select_pcd::updated_coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::select_pcd::updated_coord_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::select_pcd::updated_coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "select_pcd/updated_coord";
  }

  static const char* value(const ::select_pcd::updated_coord_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::select_pcd::updated_coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::select_pcd::updated_coord_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::select_pcd::updated_coord_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct updated_coord_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::select_pcd::updated_coord_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::select_pcd::updated_coord_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SELECT_PCD_MESSAGE_UPDATED_COORD_H
